---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: wallos
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wallos
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: wallos
    repoURL: https://vide.github.io/wallos-charts
    targetRevision: 0.1.3
    helm:
      releaseName: wallos
      values: |
        image:
          repository: ghcr.io/ellite/wallos
          tag: 2.42.2
        persistence:
          enabled: true
          size: 1Gi
        ingress:
          enabled: true
          annotations: {}
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            cert-manager.io/cluster-issuer: letsencrypt-prod
            gethomepage.dev/enabled: "true"
            gethomepage.dev/name: "Subscripciones"
            gethomepage.dev/description: "Registro subscripciones"
            gethomepage.dev/group: "k3s"
            gethomepage.dev/icon: "wallos.png"
          tls:
            - hosts:
                - &host wallos.vicsufer.xyz
              secretName: wallos-general-tls
          hosts:
            - host: *host
              paths:
                - path: /
                  pathType: Prefix
