---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: renovate
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: renovate
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/vicsufer/homelab
      targetRevision: HEAD
      path: kluster-manifests/argocd-apps/selfhosted/renovate-extras
    - chart: renovate
      repoURL: https://docs.renovatebot.com/helm-charts
      targetRevision: 39.88.0
      helm:
        releaseName: renovate
        values: |
          cronjob:
            schedule: "*/30 * * * *"
            failedJobsHistoryLimit: 1
            successfulJobsHistoryLimit: 2
            concurrencyPoligy: Forbid
          existingSecret: "renovate-creds"
          env:
            RENOVATE_X_GITHUB_HOST_RULES: true
          renovate:
            persistence:
              cache:
                enabled: true
                storageClass: 'local-path'
                storageSize: "1Gi"
            config: |
              {
                "platform": "github",
                "autodiscover": false,
                "repositories": ["vicsufer/homelab"]
              }
          resources:
            limits:
              memory: 5Gi
            requests:
              cpu: 1
              memory: 3Gi
