---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: homepage
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/vicsufer/homelab
      targetRevision: HEAD
      path: kluster-manifests/argocd-apps/selfhosted/homepage-extras
    - chart: homepage
      repoURL: https://jameswynn.github.io/helm-charts
      targetRevision: 2.0.1
      helm:
        releaseName: homepage
        values: |
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.10.5
          config:
            background:
              blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
              saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
              brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
              opacity: 50 # 0-100
            color: cyan

            bookmarks:
              - Developer:
                  - Github:
                      - abbr: GH
                        href: https://github.com/vicsufer
            services:
              - Media:
                  - Plex:
                      href: http://plex.home/
                      description: Media server
                      icon: plex.png
                      widget:
                        type: plex
                        url: http://plex.home/
                  - Radarr:
                      href: http://sonarr.home/
                      description: Movies management
                      icon: radarr.png
                      widget:
                        type: radarr
                        url: http://radarr.home/
                  - Sonarr:
                      href: http://sonarr.home/
                      description: TV management
                      icon: sonarr.png
                      widget:
                        type: sonarr
                        url: http://sonarr.home/
                  - Deluge:
                      href: http://deluge.home/
                      description: Torrent client
              - Orchestration:
                  - Portainer:
                      href: http://portainer.home/
                      description: Docker management
                      icon: portainer.png
            widgets:
              # show the kubernetes widget, with the cluster summary and individual nodes
              - kubernetes:
                  cluster:
                    show: true
                    cpu: true
                    memory: true
                    showLabel: true
                    label: "k3s"
                  nodes:
                    show: true
                    cpu: true
                    memory: true
                    showLabel: true
              - search:
                  provider: duckduckgo
                  targewidget:
            kubernetes:
              mode: cluster

            settings:
              headerStyle: boxedWidgets
              base: https://homepage.vicsufer.xyz
              language: es
              layout:
                Media:
                  style: row
                  columns: 6


          # The service account is necessary to allow discovery of other services
          serviceAccount:
            create: true
            name: homepage

          # This enables the service account to access the necessary resources
          enableRbac: true

          envFrom:
            - secretRef:
                name: homepage-secrets

          ingress:
            main:
              enabled: true
              ingressClassName: "traefik"
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                cert-manager.io/cluster-issuer: "letsencrypt-prod"
              tls:
                - hosts:
                    - &host homepage.vicsufer.xyz
                  secretName: homepage-general-tls
              hosts:
                - host: *host
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
                      backend:
                        service:
                          name: homepage
                          port: 3000

        # apiVersion: v1
        # kind: ConfigMap
        # metadata:
        #   name: homepage.css
        # data:
        #   custom.css: |
        #     /* START OF CUSTOM ----------------------------------------------------- */
        #
        #     /* fix padding between first cards */
        #     .grid.grid-cols-1.md\:grid-cols-2.lg\:grid-cols-4.gap-x-2.mt-3 li:first-child {
        #         padding-right: 10px;
        #     }
        #
        #     /* spacing between cards */
        #     .gap-x-2 {
        #         -moz-column-gap: 1.5rem !important;
        #         column-gap: 1.5rem !important;
        #     }
        #
        #     /* drop shadow */
        #     .shadow-md {
        #         --tw-shadow: 0 2px 15px 0 rgba(0, 0, 0, 0.5) !important;
        #     }
        #
        #     /* body */
        #     body {
        #         font-family: Raleway,sans-serif;
        #         font-size: 18px;
        #     }
        #
        #     /* service title */
        #     .flex-1.px-2.py-2.text-sm.text-left {
        #         font-weight: bold;
        #         font-size: 17.6px;
        #     }
        #
        #         /* cards */
        #     :is(.dark .dark\:bg-white\/5) {
        #         border-radius: 15px;
        #         background-color: rgba(24, 28, 58, 0.8) !important;
        #         padding: 10px;
        #     }
        #
        #     :is(.dark .dark\:bg-white\/5):hover {
        #         top: -2px;
        #     }
        #
        #     /* search box - inner text */
        #     :is(.dark .dark\:text-white) {
        #         font-size: 18px;
        #     }
        #
        #     /* search box - icon */
        #     .w-3 {
        #         width: 1rem;
        #     }
        #     .h-3 {
        #         height: 1rem;
        #     }
        #
        #     /* subtitle */
        #     .text-theme-500 {
        #         font-size: .9em;
        #         font-weight: 500;
        #         padding-top: 5px;
        #     }
        #
        #     /* error box */
        #
        #     :is(.dark .dark\:bg-rose-900) {
        #         display: none;
        #     }
        #
        #     /* detail boxes */
        #     :is(.dark .dark\:bg-theme-900\/20) {
        #         background-color: rgb(var(--color-900)/.5);
        #         border-radius: 10px;
        #     }
        #      /* END OF CUSTOM ----------------------------------------------------- */
        #
        #      /*
        #     ! tailwindcss v3.3.0 | MIT License | https://tailwindcss.com
        #     */
        #
        #     /* etc, etc, etc.... */
