---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: renovate
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: renovate
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/vicsufer/homelab
      targetRevision: HEAD
      path: kluster-manifests/argocd-apps/selfhosted/renovate-extras
      ref: extras
    - chart: renovate
      repoURL: https://docs.renovatebot.com/helm-charts
      targetRevision: 39.179.1
      helm:
        releaseName: renovate
        valueFiles:
          - $extras/kluster-manifests/argocd-apps/selfhosted/values/renovate.yaml
