---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: wallos
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wallos
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: wallos
      repoURL: tccr.io/truecharts
      targetRevision: 6.10.0
      helm:
        releaseName: wallos
        valueFiles:
          - $values/kluster-manifests/argocd-apps/selfhosted/values/wallos.yaml
    - repoURL: https://github.com/vicsufer/homelab
      targetRevision: HEAD
      path: kluster-manifests/argocd-apps/selfhosted/values
      ref: values
