---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: mealie
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mealie
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/vicsufer/homelab
      targetRevision: HEAD
      path: kluster-manifests/argocd-apps/selfhosted/mealie-extras
      ref: extras
    - repoURL: https://github.com/ben-kemister/mealie-helm-chart.git
      targetRevision: main
      path: mealie
      helm:
        releaseName: mealie
        valueFiles:
          - $extras/kluster-manifests/argocd-apps/selfhosted/values/mealie.yaml
