---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: homepage
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/vicsufer/homelab
      targetRevision: HEAD
      path: kluster-manifests/argocd-apps/selfhosted/homepage-extras
      ref: extras
    - chart: homepage
      repoURL: https://jameswynn.github.io/helm-charts
      targetRevision: 2.0.2
      helm:
        releaseName: homepage
        valueFiles:
          - $extras/kluster-manifests/argocd-apps/selfhosted/values/homepage.values.yaml
