---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: maybe-finance
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: maybefinance
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: maybe-finance
      repoURL: https://charts.vicsufer.dev
      targetRevision: 0.1.0
      helm:
        releaseName: maybefinance
        valueFiles:
          - $values/kluster-manifests/argocd-apps/selfhosted/values/.yaml
    - repoURL: https://github.com/vicsufer/homelab
      targetRevision: HEAD
      path: kluster-manifests/argocd-apps/selfhosted/values
      ref: values
