---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mqtt-server
spec:
  commonName: mosquitto
  dnsNames:
    - mosquitto.vicsufer.xyz
    - mosquitto
    - mosquitto.zigbee
    - mosquitto.zigbee.svc
    - mosquitto.zigbee.svc.cluster
    - mosquitto.zigbee.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: zigbee-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: mqtt-server-cert
