---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mqtt-certs
  namespace: argocd
spec:
  destination:
    namespace: zigbee
    server: https://kubernetes.default.svc
  project: homelab
  source:
    path: kluster-manifests/argocd-apps/smarthome/mqtt-certs
    repoURL: https://github.com/vicsufer/homelab
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false
