---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: home-assistant
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/vicsufer/homelab
      targetRevision: HEAD
      path: kluster-manifests/argocd-apps/smarthome/ingress

    - repoURL: https://pajikos.github.io/home-assistant-helm-chart/
      chart: home-assistant
      targetRevision: 0.2.102
      helm:
        releaseName: home-assistant
        values: |
          image:
            # Repository for the Home Assistant image
            repository: ghcr.io/home-assistant/home-assistant
            pullPolicy: IfNotPresent
            tag: "2025.2.4"
          ingress:
            enabled: true
            className: traefik
            labels: {}
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              gethomepage.dev/enabled: "true"
              gethomepage.dev/name: "Home Assistant"
              gethomepage.dev/description: "Automatizaciones de la casa"
              gethomepage.dev/group: "Smart Home"
              gethomepage.dev/widget.type: "homeassistant"
              gethomepage.dev/widget.url: "http://home-assistant.home-assistant.svc:8080"
              gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_HOMEASSISTANT_KEY}}"
              gethomepage.dev/icon: "home-assistant.png"
            hosts:
              - host: home-assistant.vicsufer.xyz
                paths:
                  - path: /
                    pathType: ImplementationSpecific
            tls:
              - secretName: home-assistant-tls
                hosts:
                  - home-assistant.vicsufer.xyz
          persistence:
            enabled: true
            size: 5Gi
            storageClass: "iscsi-retain"
          configuration:
            enabled: true
            forceInit: true
            trusted_proxies:
              - 10.244.0.0/16
