---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: mosquitto
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: zigbee
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://charts.vicsufer.dev
      chart: mosquitto
      targetRevision: 0.1.1
      helm:
        releaseName: mosquitto
        valueFiles:
          - $values/kluster-manifests/argocd-apps/smarthome/values/mosquitto.values.yaml
    - repoURL: https://github.com/vicsufer/homelab
      path: kluster-manifests/argocd-apps/smarthome/values
      targetRevision: HEAD
      ref: values
