---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: zigbee2mqtt
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: zigbee
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
  sources:
    - repoURL: https://charts.zigbee2mqtt.io
      chart: zigbee2mqtt
      targetRevision: 2.1.3
      helm:
        releaseName: zigbee2mqtt
        valueFiles:
          - $values/kluster-manifests/argocd-apps/smarthome/values/zigbee2mqtt.yaml
    - repoURL: https://github.com/vicsufer/homelab
      path: kluster-manifests/argocd-apps/smarthome/values
      targetRevision: HEAD
      ref: values
