---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: external-dns
  namespace: argocd
spec:
  project: homelab
  sources:
    - chart: external-dns
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 8.7.5
      helm:
        releaseName: external-dns
        valueFiles:
          - $values/kluster-manifests/argocd-apps/infrastructure/values/externa-dns.values.yaml
    - repoURL: https://github.com/vicsufer/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
