---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: sealed-secrets
  namespace: argocd
spec:
  project: homelab
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.17.1
    helm:
      releaseName: sealed-secrets
      values: |
        skipRecreate: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
