---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: traefik
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/vicsufer/homelab
      path: kluster-manifests/argocd-apps/infrastructure/traefik-external
      targetRevision: HEAD
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 34.3.0
      helm:
        releaseName: traefik
        values: |
          ingressRoute:
            dashboard:
              annotations:
                kubernetes.io/ingress.class: traefik
                gethomepage.dev/enabled: "true"
                gethomepage.dev/name: "Traefik"
                gethomepage.dev/description: "Ingress Controller"
                gethomepage.dev/group: "Orchestration"
                gethomepage.dev/href: "https://traefik.vicsufer.xyz/dashboard"
                gethomepage.dev/icon: "traefik.png"
                gethomepage.dev/widget.type: "traefik"
                gethomepage.dev/widget.url: "http://traefik.traefik.svc:80"
              enabled: true
              matchRule: (Host(`traefik.vicsufer.xyz`) || Host(`traefik.traefik.svc`) )&& (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
              entryPoints:
                - websecure
              tls:
                secretName: traefik-cert
          deployment:
            podAnnotations:
              prometheus.io/port: "8082"
              prometheus.io/scrape: "true"
          providers:
            kubernetesIngress:
              publishedService:
                enabled: true
            kubernetesCRD:
              allowExternalNameServices: true
          priorityClassName: "system-cluster-critical"
          tolerations:
            - key: "CriticalAddonsOnly"
              operator: "Exists"
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
            - key: "node-role.kubernetes.io/master"
              operator: "Exists"
              effect: "NoSchedule"
          service:
            ipFamilyPolicy: "PreferDualStack"
            labels:
              metallb.universe.tf/address-pool: private-pool
          extraObjects:
            - |
              apiVersion: cert-manager.io/v1
              kind: Certificate
              metadata:
                name: traefik-cert
              spec:
                commonName: traefik.vicsufer.xyz
                secretName: traefik-cert
                dnsNames:
                  - traefik.vicsufer.xyz
                issuerRef:
                  kind: ClusterIssuer
                  name: letsencrypt-prod
