---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: tailscale-operator
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/vicsufer/homelab
      path: kluster-manifests/argocd-apps/infrastructure/tailscale-operator-extras
      targetRevision: HEAD
      ref: extras
    - chart: tailscale-operator
      repoURL: https://pkgs.tailscale.com/helmcharts
      targetRevision: 1.86.5
      helm:
        releaseName: tailscale-operator
        valueFiles:
          - $extras/../values/tailscale-operator.values.yaml
