---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: cloudnative-pg
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: https://github.com/vicsufer/homelab
      targetRevision: HEAD
      ref: values
    - chart: cloudnative-pg
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.23.2
      helm:
        releaseName: cloudnative-pg
        valueFiles:
          - $values/kluster-manifests/argocd-apps/infrastructure/values/cloudnative-pg.values.yaml
