---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: traefik
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/vicsufer/homelab
      path: kluster-manifests/argocd-apps/infrastructure/traefik-external
      targetRevision: HEAD
      ref: extras
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 34.3.0
      helm:
        releaseName: traefik
        valuesFiles:
          - $values/kluster-manifests/argocd-apps/infrastructure/values/traefik.yaml
