---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: cloudflared
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: cloudflare-tunnel-ingress-controller
      repoURL: https://helm.strrl.dev
      targetRevision: 0.0.18
      helm:
        valueFiles:
          - $values/kluster-manifests/argocd-apps/infrastructure/values/cloudflared.values.yaml
    - repoURL: https://github.com/vicsufer/homelab.git
      targetRevision: HEAD
      ref: values
