---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: sealed-secrets
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/vicsufer/homelab.git
      targetRevision: HEAD
      ref: values
    - chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.17.1
      helm:
        releaseName: sealed-secrets
        valuesFiles:
          - $values/kluster-manifests/argocd-apps/infrastructure/values/sealed-secrets.yaml
