---
fullnameOverride: synology-csi
clientInfoSecret:
  name: synology-csi-client-info
storageClasses:
  iscsi-retain:
    isDefault: false
    disabled: false
    parameters:
      fsType: ext4
  iscsi-delete:
    isDefault: true
    disabled: false
  smb-retain:
    disabled: true
  smb-delete:
    disabled: true
  nfs-retain:
    disabled: true
  nfs-delete:
    disabled: true
