---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.deployment.repository }}:{{ .Values.deployment.tag }}
          imagePullPolicy: {{ .Values.deployment.pullPolicy }}
          env:
            {{- range .Values.deployment.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: DB_HOST 
              value: {{ .Release.Name }}-postgresql
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.existingSecret | default (printf "%s-postgresql" .Release.Name) }}
                  key: password
          {{- if .Values.deployment.extraEnvVarsCM }}
          envFrom:
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.extraEnvVarsCM "context" $) }}
          {{- end }}
          {{- if .Values.deployment.extraEnvVarsSecret }}
          envFrom:
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.extraEnvVarsSecret "context" $) }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.deployment.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: {{ .Values.deployment.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
