---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-{{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
{{- end }}
