---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synology-csi-client-info
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yaml: AgBUDB9AqSyOtrxLOXyIg5X1q8g+CLTAEWJQE2OEJH3l7/frp7RvAuYjT6GeBBI2d1XLs2pXJra0JKxI3oQdZeVx1ZNnKqcj+KxGiz1DwwhEH0CUMujmev0Ej5fEeS2TgQJQqLdwQs8zzKgq3/wGsEzBzDf+FPwLvUXmOTtn1UKaP1yL9ox1Ux4bk1Pyd1octKx2T3LgQMbFw4qgud+tiqT37i42TdzdBNPghOpqSe/66spUbm9SqYPYlMSc3V4+yPjsOAkOnxjamu5yo5mdtBIruEW7lcU0S8N2hzahDUfQ7C4BL8j99LwbBS2AyJrK8eb+/70uBmrfuZKTDUZ25sGCJPtRARU+k8O5iI+j1BurdzlmifnlKDV1jNfKWz5DU6hAIg+cVPtUwwe9/0eHQ8ZHQsCKrbo/NX5I/leDtOiUpwvofRFMK5hI4n4oJIt3vwtOBKI5aCP/DMCZQ1jKG+yQZJAWlMdUBdMOx0y8Z3Aq2dxsYDajXq3CFw9BZRgZwwTFLIc8+obXlOme5aVUxhEb+PGU8uk38bUKrIfEEsBzZl7YnlN3P8JOxAIMX26jVU25sDyie9CZ3rmMMEKrMPd7E9/i+xzmQWDKaunHHmBkArVArdyQTIpcKUV5qDAMT1DZU5qRI3s589aG5DcjDVS1T80Xv74o71jr2rviCBYfIO7czSJHsSSzhBp5lKYqylFk9ubc5oWmBUyckBPXY5tU+c4y1Vkc4kSw6gPxOmHxmTUthP67cyVeAN2Jc3VzNlUzut4ADjSasj2CSSV334rnY+9dtt3rZ+X0ZExgIsWKopsZc1er40Ma9GA0KzTx5Qe2g/4qkOiZmVhPYeGtRg==
  template:
    metadata:
      name: synology-csi-client-info
      namespace: synology-csi
    type: Opaque
