---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synology-csi-client-info
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yaml: AgBk936dO7pByzA+6t2K27DMa+PImj7owmBqJN2/K/hM1Mop5tmnCclB5Et/xz4loVFBTFtbbFD8yEa1omZQSRw4JoazesLCTaiNLtdjfLGiDz7YTt/EGmfLHkAcADJP5aTXhzJB7NlX9ZoImxWIYHFTlx8azjdgnXDaVN+ItX43xDg5P1DLN2Naj0tCudv9bZHKCgq+89TL6q9nvtJWuzuybTfleS8sQidK0mVVNb856lbtvMwIYgarjoJKXJAakBdrpHu/+CPwSSwAooOBnhBEDiRkxhafBPHm8IjAJGU1IKS/RSBw+so1xwd/Gnu0jkJtHbxhJNwOAxbG6VBJwVqgZ0lVhfTmsHeyfNtX6N+uBfEskQaCLwrBcS4PXFq0fpVb9ClpRFFM9QOOImE7xoNPsFBrta2Z3kxv6l9dds48e9/Q8k1hcsrtT5SBQUI9ib8beAvKAFtLcTfPcOm09e5a67bX6T3M54A34VrdMCJQp6LcUQvhjsfSUq54KjeW0QhsDgf2WRt45ZI3L8ZwOFlVZq22BYsFy/TMmIo5PcpEfS1h1EGdvrccioIZk6PpW11P8zDjjvKKF5JK20FwvcTCrCvHZrwXEZqH09fJVFKfwJF+QVzwhgPOyak0B5WYdlyb+Ad2nwH5aESPgTHNbnq191RkeL9Xze/QFzHKsjT2qtoG1y8SMHMzNYpntqda7Fh9eNacGsVyPJ6NWnMjjlpF2CLXrTBVf4R5b/tb0q+Ke3l2YRQMvnXQ/xc0w06RWlbWc076Aoo35jY0IJegOQAOiavmee3LH5oxWGAWoASNAHG3IwWQ6TP2ckRj2AAguwmgb6xvQ15gqPJ6wvdU
  template:
    metadata:
      name: synology-csi-client-info
      namespace: synology-csi
