---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-password
  namespace: maybefinance
spec:
  encryptedData:
    postgres-password: AgBFerWrxWfNFLtjC3/xxUgmBv9A1z8HBZU7ufhs4sk8aS4B6lT94XNvucMhRQSPCxYMWIMKWQ6KLKwEOXEkqUGAJiBe1qNam3LZN2lgkh6/1OliUUYMiOY25ThZMf4ULR48sKaRFfe1MKbm1Z4BuTzwB4be1S1hBIQ/JJoI7qH/rCIceR/l3kGtizjpSGTTr1e8a693m5LZQ9yHUSw79K6xDVkDNRj4tB/PWP6F52e5jnzvclwd8JXc0rsDqIGF99Xz4m8BTqz4iZmfX2E453NnCs6cyVmkKojulQuvtzWVhSGKfujgtIMss6KnpwWfkV11+k2PiphcVwdx7/Lnq910M6eKX8Z1RRovj+vbXSO07EzJH3VWHd04wOEQmWFXCFCFmoMVVHeYi7pH97NEeJwnlWim1nNNKIF5U3tmsqQeI7eiZ9fI+nypoUHiJwyMTfUx8uJUdiu/F6fDCwmHiTMwJkkfe1Dyw29BUdQ2qQVsIjo3ju0ujrY1rf145XwOvEXEfVSE+EbqEkMyR8hlijkVWW43S/U+l0U6KKdTLlPVX3F7tQvFch7W80zBjyXVQmomPjnFtKejFZbhX2JA4MKjEL14V1reLwTKHn1WXSSpxZdgYxjXCA1mH75NqmI5T1Mg2FDx4ueDCcINbL41gYAK61KDYZhgumcja1pPGP3eWauEjN2zxCjZaZcfFJssD8dQp0jP0A==
    password: AgBFerWrxWfNFLtjC3/xxUgmBv9A1z8HBZU7ufhs4sk8aS4B6lT94XNvucMhRQSPCxYMWIMKWQ6KLKwEOXEkqUGAJiBe1qNam3LZN2lgkh6/1OliUUYMiOY25ThZMf4ULR48sKaRFfe1MKbm1Z4BuTzwB4be1S1hBIQ/JJoI7qH/rCIceR/l3kGtizjpSGTTr1e8a693m5LZQ9yHUSw79K6xDVkDNRj4tB/PWP6F52e5jnzvclwd8JXc0rsDqIGF99Xz4m8BTqz4iZmfX2E453NnCs6cyVmkKojulQuvtzWVhSGKfujgtIMss6KnpwWfkV11+k2PiphcVwdx7/Lnq910M6eKX8Z1RRovj+vbXSO07EzJH3VWHd04wOEQmWFXCFCFmoMVVHeYi7pH97NEeJwnlWim1nNNKIF5U3tmsqQeI7eiZ9fI+nypoUHiJwyMTfUx8uJUdiu/F6fDCwmHiTMwJkkfe1Dyw29BUdQ2qQVsIjo3ju0ujrY1rf145XwOvEXEfVSE+EbqEkMyR8hlijkVWW43S/U+l0U6KKdTLlPVX3F7tQvFch7W80zBjyXVQmomPjnFtKejFZbhX2JA4MKjEL14V1reLwTKHn1WXSSpxZdgYxjXCA1mH75NqmI5T1Mg2FDx4ueDCcINbL41gYAK61KDYZhgumcja1pPGP3eWauEjN2zxCjZaZcfFJssD8dQp0jP0A==
  template:
    metadata:
      name: database-password
      namespace: maybefinance
