---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: maybe-secrets
  namespace: maybefinance
spec:
  encryptedData:
    SECRET_KEY_BASE: AgBfcW5UIazod/th2IgKVRevCQJ+7nQpEhePqUhd91gawMpztUQBImOZuN2l0O5SkIL4Xm9Wk8+4O5pr6zWgwPwgziNW8LdfGzY3bakb0OmChkXPrztVsDyjcHxif23+yGZT94oQd4DYbr664rCsv03l7r1qa2CtycAkU98ncwncf4t08piVljQDqcqzAXzVcElaE8trBaQW49lLp7ztmkz/uASZskjMzX7rt5RNdxZb160EP+iKU4fSquSMEOunv9hwI/ZPRBZD/KuzY842rjUmSP/mi7HO0RCZwYHX5uO0XvwiCCsugvgQbmO63gWIfaIxdgU7c+bcnUhMHsYvDClgJu26DPhcDVrpxnNppbqavBwY023d1D/dKWpQp2G8OIcEg599uPxVIlBeWhnUFZ5OAxj2esYK3gUEUENjeqbJn865NHUiz8+wzOL4ymuxUB6BYVStp5bAMlTKXV2p01fW+VBpiQqTV6mdioe8wOlxPAsYDH65CzIhiYmjrWk0R8khiimv3aSi1riWz9hbHAzXH2LHvjPqNf4M4N9urZlaHPOeCashzmBZkrt2hZee4/jH6m5K6RrZVpmPhy0/t64wHSq3r0TmffFH73IX/+C1qgZzwZcBCBJU7pfOf8DTadpLEnBsHtP6Mx9ZQ1MYTNvogS4B04Qc9NN+T1pOBPvkakWJVwaQkfya/rXnNAwpTrhcQMpGayR1CdkuZ/Y/kWmkApAgwzetXJZgoLWk21eOAQ7IGpKcEntKPa55JfEvLlSGEmhvSO+X2M0adH3ujTzmtpmjFFnqy2Y7A8y2UXYNasruZQwME4b3ye4Yl0ZyNJaOKZBqdZScp9a02d1aYC9cdl9iDniTHzejRhh8z6tPkw==
  template:
    metadata:
      name: maybe-secrets
      namespace: maybefinance
