---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: prowlarr
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mediaserver
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://charts.pree.dev
      chart: prowlarr
      targetRevision: 1.40.0
      helm:
        releaseName: prowlarr
        valueFiles:
          - $values/kluster-manifests/argocd-apps/mediaserver/values/prowlarr.values.yaml
    - repoURL: https://github.com/vicsufer/homelab
      path: kluster-manifests/argocd-apps/mediaserver/values
      targetRevision: HEAD
      ref: values
