---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: prowlarr
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mediaserver
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.pree.dev
    chart: prowlarr
    targetRevision: 1.40.0
    helm:
      releaseName: prowlarr
      values: |
        env:
          TZ: Europe/Madrid
        image:
          repository: ghcr.io/onedr0p/prowlarr-develop
          tag: 1.26.0
        ingress:
          main:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              gethomepage.dev/enabled: "true"
              gethomepage.dev/name: "Prowlarr"
              gethomepage.dev/description: "Rastreador torrent"
              gethomepage.dev/group: "Media"
              gethomepage.dev/widget.type: "prowlarr"
              gethomepage.dev/widget.url: "http://prowlarr.mediaserver.svc:9696"
              gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_PROWLARR_KEY}}"
              gethomepage.dev/icon: "prowlarr.png"
            tls:
              - secretName: prowlarr-general-tls
                hosts:
                  - prowlarr.vicsufer.xyz
            hosts:
              - host: prowlarr.vicsufer.xyz
                paths:
                  - path: /
                    pathType: ImplementationSpecific
        persistence:
          config:
            enabled: true
