---
image:
  # Repository for the Home Assistant image
  repository: ghcr.io/home-assistant/home-assistant
  pullPolicy: IfNotPresent
  tag: "2025.5.3@sha256:8a99004ff832dbd535e6ac4d141042bc31141ff6a86b4d5bb288b3680fbceac1"
ingress:
  enabled: true
  className: traefik
  labels: {}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Home Assistant"
    gethomepage.dev/description: "Automatizaciones de la casa"
    gethomepage.dev/group: "Smart Home"
    gethomepage.dev/widget.type: "homeassistant"
    gethomepage.dev/widget.url: "http://home-assistant.home-assistant.svc:8080"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_HOMEASSISTANT_KEY}}"
    gethomepage.dev/icon: "home-assistant.png"
  hosts:
    - host: home-assistant.vicsufer.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: home-assistant-tls
      hosts:
        - home-assistant.vicsufer.xyz
persistence:
  enabled: true
  size: 5Gi
  storageClass: "iscsi-retain"
configuration:
  enabled: true
  forceInit: true
  trusted_proxies:
    - 10.244.0.0/16
