---
image:
  repository: eclipse-mosquitto
  pullPolicy: IfNotPresent
  tag: "2.0.22-openssl@sha256:d219d3a72847f3aed6a1d66975972d3b17f86e39e8f6f6b86b4088b879c1a2d6"

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Mosquitto"
    gethomepage.dev/description: "MQTT broker"
    gethomepage.dev/group: "Smart Home"
    gethomepage.dev/icon: "mqtt.png"
  hosts:
    - host: mqtt.vicsufer.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: mqtt-tls-secret
      hosts:
        - mqtt.vicsufer.xyz
deployment:
  volumes:
    - name: certificates
      secret:
        secretName: mqtt-server-cert
        defaultMode: 420
        optional: false
  volumeMounts:
    - name: certificates
      mountPath: "/tmp/certificates"
      readOnly: true
resources: {} #TBD
general:
  logType: notice
auth:
  enabled: false #TODO Enable auth with mtls
  users:
    - username: zigbee2mqtt
      password: $7$101$T1RBXD5MGIImHq8g$hSCHVAyZtAif0qN9Fhuam9mVCd0xLomREHIwzdreGjjADCQewz9VpfhK6AumcZyVFHFpHd2EhZdqU+Lq7393Xw==
      acl:
        - topic: "zigbee2mqtt/#"
          access: readwrite
  mtls:
    enabled: false
    certPath: /tmp/certificates/tls.crt
    keyPath: /tmp/certificates/tls.key
    caPath: /tmp/certificates/ca.crt
