---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: mosquitto
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: zigbee
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/vicsufer/homelab
    path: charts/mosquitto
    targetRevision: HEAD
    helm:
      releaseName: mosquitto
      values: |
        image:
          repository: eclipse-mosquitto
          pullPolicy: IfNotPresent
          tag: "2.0.20"

        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            gethomepage.dev/enabled: "true"
            gethomepage.dev/name: "Mosquitto"
            gethomepage.dev/description: "MQTT broker"
            gethomepage.dev/group: "Domotics"
            gethomepage.dev/icon: "mqtt.png"
          hosts:
            - host: mqtt.vicsufer.xyz
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
           - secretName: mqtt-tls-secret
             hosts:
               - mqtt.vicsufer.xyz
        deployment:
          volumes:
            - name: certificates
              secret:
                secretName: mqtt-server-cert
          volumeMounts:
            - name: certificates
              mountPath: "/tmp/certificates/"
              readOnly: true
        resources: {} #TBD
        auth:
          enabled: true
          users:
            - username: zigbee2mqtt
              acl:
                - topic: "zigbee2mqtt/#"
                  access: readwrite
          mtls:
            enabled: true
            certPath: /tmp/certificates/tls.crt
            keyPath: /tmp/certificates/tls.key
            caPath: /tmp/certificates/ca.crt
