---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: mosquitto
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: zigbee
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/vicsufer/homelab
    path: charts/mosquitto
    targetRevision: HEAD
    helm:
      releaseName: mosquitto
      values: |
        image:
          repository: eclipse-mosquitto
          pullPolicy: IfNotPresent
          tag: "2.0.20"

        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            gethomepage.dev/enabled: "true"
            gethomepage.dev/name: "Mosquitto"
            gethomepage.dev/description: "MQTT broker"
            gethomepage.dev/group: "Domotics"
            gethomepage.dev/icon: "mqtt.png"
          hosts:
            - host: mqtt.vicsufer.xyz
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
           - secretName: mqtt-tls-secret
             hosts:
               - mqtt.vicsufer.xyz

          extraVolumes:
            - name: certificates
                secret:
                  secretName: mqtt-zigbee2mqtt-cert
          extraVolumeMounts:
            - mountPath: /dev/ttyUSB0
              name: usb
            - name: certificates
              mountPath: "/tmp/certificates/"
              readOnly: true
          resources: {} #TBD
          auth:
            enabled: true
            users:
              - username: admin
                # "admin" password in sha512-pbkdf2 format, generated with mosquitto_passwd
                password: $7$101$T1RBXD5MGIImHq8g$hSCHVAyZtAif0qN9Fhuam9mVCd0xLomREHIwzdreGjjADCQewz9VpfhK6AumcZyVFHFpHd2EhZdqU+Lq7393Xw==
                acl:
                  - topic: "#"
                    access: readwrite
              - username: zigbee2mqtt
                # "admin" password in sha512-pbkdf2 format, generated with mosquitto_passwd
                password: $7$101$T1RBXD5MGIImHq8g$hSCHVAyZtAif0qN9Fhuam9mVCd0xLomREHIwzdreGjjADCQewz9VpfhK6AumcZyVFHFpHd2EhZdqU+Lq7393Xw==
                acl:
                  - topic: "zigbee2mqtt"
                    access: readwrite
