---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.20
  share: /volume1/kubernetes
  subdir: /${pvc.metadata.namespace}/${pvc.metadata.name}/${pv.metadata.name}
  mountPermissions: "0777"
reclaimPolicy: Delete  # Use "Retain" if you don't want automatic storage deletion
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
