---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: talos-backups
spec:
  roles:
    - os:etcd:backup
---
apiVersion: v1
kind: Secret
metadata:
  name: talos-backup
  annotations:
    kubernetes.io/service-account.name: talos-backup
