---
apiVersion: v1
kind: Service
metadata:
  name: external-pihole
spec:
  type: ExternalName
  externalName: pihole.home
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-route
spec:
  entryPoints:
    - websecure
  tls:
    secretName: pihole-cert
  routes:
    - match: Host(`pihole.vicsufer.xyz`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: external-pihole
          port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
spec:
  commonName: pihole.vicsufer.xyz
  secretName: pihole-cert
  dnsNames:
    - pihole.vicsufer.xyz
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
