---
image:
  repository: ghcr.io/sct/overseerr
  tag: 1.34.0@sha256:4f38f58d68555004d3f487a4c5cbe2823e6a0942d946a25a2d9391d8492240a4
env:
  TZ: Europe/Madrid
  LOG_LEVEL: "info"
ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Overseerr"
      gethomepage.dev/description: "Peticiones mediaserver"
      gethomepage.dev/group: "Media"
      gethomepage.dev/widget.type: "Overseerr"
      gethomepage.dev/widget.url: "https://overseerr.vicsufer.xyz"
      gethomepage.dev/icon: "overseerr.png"
    tls:
      - secretName: overseerr-general-tls
        hosts:
          - overseerr.vicsufer.xyz
    hosts:
      - host: overseerr.vicsufer.xyz
        paths:
          - path: /
            pathType: ImplementationSpecific
persistence:
  config:
    enabled: true
