---
image:
  repository: linuxserver/prowlarr
  tag: 1.35.0-nightly@sha256:f2f299a93ce4afaec6b032f38d25ec6af872bb2984268b3aa9019daba9e3ea11
env:
  TZ: Europe/Madrid
ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Prowlarr"
      gethomepage.dev/description: "Rastreador torrent"
      gethomepage.dev/group: "Media"
      gethomepage.dev/widget.type: "prowlarr"
      gethomepage.dev/widget.url: "http://prowlarr.mediaserver.svc:9696"
      gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_PROWLARR_KEY}}"
      gethomepage.dev/icon: "prowlarr.png"
    tls:
      - secretName: prowlarr-general-tls
        hosts:
          - prowlarr.vicsufer.xyz
    hosts:
      - host: prowlarr.vicsufer.xyz
        paths:
          - path: /
            pathType: ImplementationSpecific
persistence:
  config:
    enabled: true
