---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-secrets
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_HOMEASSISTANT_KEY: AgCDZd75imc4oroQ+ciVwF/ROgX1hC2LZGwkLkZegotQCr9CV/aGKRNU78q3+m0q0A31NYVnqutZzt/HQzFkAdwiCbGRzT9YwTYzI1aXoJOlRhfwAdligUNArCxWz5CwFWSMHZD9+QJ6hCG3N3k2hkOdTK9+KdrpZXVMGIWi3lTtKKWW3b18IWaqHnOu/SM9Gd+dw/9vWCzURrOhjMZMJnmrzuy8cxUEux0l5QRSwfYEIs7fjr1wI0NqiQsBRO9E54G5jEhe4kZJZiNNw9jHYkUVVgXojoJLkxvd09HJLD16Wgmst5YOAxljHozpYX71btc/DOrz0L5XkrP0p0O01yVkRAzjAyFkdoKTTWlCfn8ROwW5Skq0JDwNSEE6rPt3X3hPlKAu+1HZL/ICEArSDvJpwHsC9G/HhXgd1VBdMzYdFHf/Z3tySx2O4PFiRPTiksCkakNm7SJNpRMiT4UcJ2HM+y2jh8WFybgj6oCDwt3WBI0EQ6cssIKK1fjyVonFfQo7YAmu1fG44PnDSicchuEg3BSsDU6sblAcw3/s41e4Ifbfc2xsbvibLKydjrpVCA7T5vWQ80QTd0oKhOCUep5FjIlwC4eGrwjqfrR/etG/kIuFMMkJVGrDg9u3/lH8HR5lghjKzwVFyJcl/dqSAmHkidnssDWCXa7te7mHKJwCNsg/9zOI7Zp/F3GsTOsIi92jRMVzfyd8jppQGhKB2S7//APiS1rcwgeOAclzQfAZdxi5Ln2deawYnAuLRca/tUAbxF4BjEo4xWOS1fFDMFgFj6r9K1Ye1Qhyrg5FbvMI/enOWmbbD4oGk+Jdf56G5S1EuPWYExa6/wtWxbTK8hTBsfDE0dB1rPmrRs/EuFegLupwYN0RP/HSc/3NxJaalooOmWfWyBRPWOcGI+mIVZpxaKKUbYiTrTYbC2Y/NuoxERTtHaSko8Y=
  template:
    metadata:
      creationTimestamp: null
      name: homepage-secrets
      namespace: homepage
