---
#helm upgrade argocd argo/argo-cd -f argocd.values.yaml --install --namespace argocd --create-namespace
global:
  domain: argocd.vicsufer.xyz


configs:
  params:
    server.insecure: true

controller:
  resources:
    limits:
      cpu: 1000m
      memory: 1536Mi
    requests:
      cpu: 500m
      memory: 1536Mi

dex:
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 64Mi

server:
  ingress:
    # -- Enable an ingress resource for the Argo CD server
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls: true
  # certificate:
  #   enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi

repoServer:
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 1024Mi

applicationSet:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

notifications:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

extraObjects:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: applications
    spec:
      source:
        # repoURL: github.com:vicsufer/homelab.git
        repoURL: https://github.com/vicsufer/homelab
        path: kluster-manifests/argocd-apps
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: default
      syncPolicy:
        automated:
          prune: true
  - apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret # Circular dependency, move this to another app just to store repo credentials
    metadata:
      name: docker-io-helm-oci
      namespace: argocd
    spec:
      encryptedData:
        enableOCI: AgCwD7Ed1QWKDC2YNvN02nnjB1q2c17PO3CM8rmzcJXWdVUYrmeYRZ24M8PrC+a7d32WbgJmeyUcgCit50e5V1cVA9EDMC8a5otOv+LYXsPAl4ajDB3CZwG8dVEj4LsRv4RsMxUvd7KuvkwQxGLV0eFIVrzoEndUCDhjs9uosmEW6B0cJKWePrhMMMNo+EepVEZNG88ShVj3dqmeVKrgCHzUeDnmwt9bNGNnmGR0wHWVXAMhFT9Mahk1YqLbP5YrormtEm5+gIJ5X5+wbcBo9H1v4KzuU+DiKdYunJtQJiauT/XbzN5PkTkIQHvwm1olnicnfM/T2ltxzl3as/MYDQlpVxKDAM8urCRhfeqVldxEp1yKOtNG4NBGdEHS3G2/LjjeV/neDwsy6dDDDieiCMTj52869ObHrW5gEsx3qd92+Vldq8tizuyrGtdOwhsSTn7JrHRAGEIT6RSGcHF7pznQe7y3OYztdirx+5D0fDDvxqYi+DwXsCAYCsGYmKXlUB6EvvOS4qDau3dqW8ZpFnPzd3Dg4oKTGQrvcc9KKg9IG0HLe5HcqzyM/hw1YYpc2Rt4kmbYYbfNKT896tjYFlgEbJ94DL1/zrdtYv94g3pSezj7UdlnUERVv+9BbGTTh2fENMewXovYP/37R6487lWNjJkqZOProh0HehpxEksIMbVbhvtTp9XQ7UbUuHbxgSq4BDOjo8FZDw==
        name: AgBUCxGakr4vP4gBjt9gdaks3uYQTUq8bbqk/cqUrcnt0d5GzEsNWPebVq4UuQf4KvIXToaljlJ8PItiQj+jbeq7FyXztyGI3Mk2F8i8kiBBYbDNGh/llpCZAamp7hv/FcNcwRKz9qPFS7rWaIMeq7C/RT0Xt2LwYVGLvOJYM9syUHMNSeCQ5cWdTArbaHAOBEDrRMcB487eMUSMNfyWl/dl/8sZMhYI4+BRezkjj3i7Ue2Te5oGCoA9a3j8kmilnz1ORauChCrY86NrGtywoPGA30Zp9CQwCwZqQLbZmTXAhB0GenfJEO7PJAovevTX5uaMMygcgZbgJbELiXEpROcIwrJxktb9euFq5Hq5gzdVzQLDfJA8q3+ZF9D3A7us5mzDYoy025WRnr0cOYiz/PTUjR0gGKIEjO0LVluUmiZGI5pSGHnAW7+3fFN/JwFTORKYDpki+Gi7vXfGiirKU+NNGgIZMurXdyoJJ/jq0GxPZYuY0n/gLF05KI8i+D2jLnDt46rwzb3aJ/DGFbfN/scni7GjslcRPBP/8Yx0n0WgZSJfxFxts3ejmKgCPMVNm+fpFnmGYyHGlA+EasERgOtLQvuI81h1UirSPi9UUGd4WEYFsOu8fJKLqYDfisp4+ypJXB1TK5YKt4aPfIThpI4Y3x9+3wjeEj6owmFgDBWBaqpoqA4J5//ksJe42cDapwiAuD76NLipTMno+1lY5nsZuSqSew==
        type: AgC2GNaXGh5GucKhp9iM40ct1AtI+kbyBrr0Tg6hKrGaLZyn0X+mjSGV2V8PPIE1l6CRlTmwy3FkKiCEwzGLg8UBrwEwqkSZeOLDpVYS2FlPDtszogN1mOTh5ZOoVrTbH0GzfG1atwx/MxVfxeciT1cClJmbhClhEc4A3FMCU5pQDY/CSKNoGhxxBRNABoseC8mal08EIhs4p4FjHity0T4BFIqTYl59LKoOyuR6eAuD09t8AszGNEv8JO7cKpzNaqdbB6GLqVps9szOyObuZzT/NWhktGdgwj6n44xl2Vpq7IJ/n/89/LLW3sMBcOayWsRBMD9ZzHxkz7r4piBlTYvhJRfTveHVmcPXbUuuphS6aiOegn4t08RXk5V2WAzr/SN8Cf13wky7rObwp9wcVZY3CAgWg8tTwzZy3jGU/AZG9oSNhHujrxib18dogFbUEgKwbmYrIosPfF7WSSslmwenvFtgIyl53rrXsH1pbn//+dncaZpWTvcgyHzYB2t9bwraWmizV5rByyVbvSPJpLma8ZJ+F1s2ZgI3t80GBRXsF18iA5ZAZYExAKqkjfmkd5e0E8R+tRvQHCAY5KW4Pl6VlW/BWrBg9indCs/PV2A7eW6RNi7uPLsMNVg0Igm92KSwcS6h5QXkvxttTdg7s0qMpBDMbtA9fxoONeB//PIbu1rGjqHNgizzDGF9QJEDG6eF1wJVZKtgzA==
        url: AgCuvMrMlHKexwCtjSdsivMHMK1zMT65/rdM69LRWo3x+sAfk51OypsndJm4N1suI0raq7I0N8/1JcX5XAUSnBrCrbx48RaFgM6d7HpTdjeUwVTgdAFtzQgYQzmBAAtwvRkG0pQlOml7lOVIiae1MPd1b2w1WeJcVMZyrbBHelDU5VEoaZjzWcb0heCm+RSoM2Aaj6cKRB5/E43qEtHapX5ZC7SzzUu3Rrzw6n7jV5CpSfTAUjQkahTyp/Ng/c6dcO9fU6i5fRKr0H6UZ6Ire2z4sudlROCm66RfNdHCMKxmRRpv+M2VtgmuuBaMcXMGHHfYR5eoAtIfygk0flOwkyRDZGiDXioCWovjvw+II63sSOGxCgMX4LdRqgpg9odk9RHxihVV5Vm4Mx27+EO5Mq5ozI9bvrCNZCeJNmtf3SSIWlmXGbxu8cqJ1jTBnlt6LefcqgBmStgHLulq0CaeAkOFme5rFAcOxdKAn9YEOR4iFuQaHUR8pK+h2lR5CvNpqbdYvtmM1zhHqwJaYShEQG7LoRGBs/DClpcnmoqKRVJNhxF6m1A3Dzb6peEou98H83GhKqCUweNZso+uTnpleYa2soLioMxKcFcKGrwEBITqJ8+J6pgc3hePC+S4x/jSoh7OuiSkI0I5RLueejntTa5vVwGRbqNTMH8fJZDfb95QGw9PpQ8gJIwwBjdHxOuwOJz/9GXkySyxqRRVi4u4LTSh0pJspC5MeUi3vniwIX3gbsU4YKoXMyeNoDM2LsiLQI0=
      template:
        metadata:
          labels:
            argocd.argoproj.io/secret-type: repository
          name: docker-io-helm-oci
          namespace: argocd
