---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-creds
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgBhdWp3cnQwjYC1m2WS6Ca92HQ2kww8XIuGnhQQ5BIGozJiJWrqnmHKIoEVwF8fHhErMFCafZmWxK18p+zx8PK4B8ikRTcA1wY1LiycFF5Ro/T0d3paj1VRNzKTHJlgiAoz7LnXxJkD5BocRziDKYiWgfDsigHZUV31pQbBu530DHAfCl1dMBd3DRBL6g+WAjC14D3ic6zMynr5zjP/DAA81VyzWZbsLBJwd0xFi6Rzw6QscxOUmz/kEtKc7U23DyJkr9HcTeMC3+OKV/ahnHkxT8/jqgDrRED9BAR/mtMcIMVqbiwal67yXdutJya0MoKpNUCKOmUYdvme11xeRX+shuFvzFjeuiK4wBbEeHGxSHZUlBaJYzKbqIH31JUyWhg13bhg9bwNv1H4dWyKZKWzroP6FYOFlXkScmKZuxNJvHMdVW/aS/5IkS4KyiYu1sseeMjsjRMITSew1nbA+1lhq6p9cupqx92INm0fU460sNQ7pn4K3G9SBiHGDunPFb+0OI2a0hDAIdb3fE9TMIPD4YlST/GcmeWFIVQpy6ft+AfQxW3TsG5heXjPKSmOWdupRkKwE4v35tfoLzQuyqPJp9KwlHsyPPov4jjzWx8uMIjw+GOvtsmLPpqGE9h8mkyuzMeDyhe+P2WUA6RkqLUDA+9cq3lyMe1XLByHFo9r0AfqQe1lj/paGfOaKnsaMRHIJkS1AtyJREqUtu8Tkye2ZZLGHrgqbNE3woJHXqY3aZxPzK2LDAJV
  template:
    metadata:
      name: renovate-creds
      namespace: renovate
