---
image:
  repository: ghcr.io/gethomepage/homepage
  tag: v0.10.9@sha256:b6d732817572f9af99ec168b10641b8f7820f30cfa5a5cc5c68f1e291804bec8
config:
  background:
    blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
    saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
    brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
    opacity: 50 # 0-100
  color: cyan

  bookmarks:
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/vicsufer
  services:
    - Media:
        - Plex:
            href: http://plex.home/
            description: Media server
            icon: plex.png
            widget:
              type: plex
              url: http://plex.home
        - Radarr:
            href: http://radarr.home
            description: Movies management
            icon: radarr.png
            widget:
              type: radarr
              url: http://radarr.home
              key: "{{HOMEPAGE_VAR_RADARR_KEY}}"
        - Sonarr:
            href: http://sonarr.home
            description: TV management
            icon: sonarr.png
            widget:
              type: sonarr
              url: http://sonarr.home
              key: "{{HOMEPAGE_VAR_SONARR_KEY}}"
        - Deluge:
            href: http://deluge.home
            description: Torrent client
            icon: deluge.png
            widget:
              type: deluge
              url: http://deluge.home
              key: "{{HOMEPAGE_VAR_DELUGE_KEY}}"
    - Orchestration:
        - Portainer:
            href: http://portainer.home
            description: NAS Docker management
            icon: portainer.png
            widget:
              type: portainer
              url: http://portainer.home
              env: 1
              key: "{{HOMEPAGE_VAR_PORTAINER_KEY}}"
        - Synology:
            href: "http://192.168.0.20:5000"
            description: Almacenamiento en red
            icon: synology.png
            widget:
              type: diskstation
              url: "http://192.168.0.20:5000"
              volume: volume1
              username: homepage
              password: "{{HOMEPAGE_VAR_SYNOLOGY_KEY}}"
  widgets:
    # show the kubernetes widget, with the cluster summary and individual nodes
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "k3s"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        targewidget:
  kubernetes:
    mode: cluster

  settings:
    headerStyle: boxedWidgets
    base: https://homepage.vicsufer.xyz
    language: es
    layout:
      Media:
        style: row
        columns: 6


# The service account is necessary to allow discovery of other services
serviceAccount:
  create: true
  name: homepage

# This enables the service account to access the necessary resources
enableRbac: true

envFrom:
  - secretRef:
      name: homepage-secrets

ingress:
  main:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
      - hosts:
          - &host homepage.vicsufer.xyz
        secretName: homepage-general-tls
    hosts:
      - host: *host
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: homepage
                port: 3000
