---
image:
  repository: leantime/leantime
  tag: 3.5.5@sha256:9a2c81a5f5417fd5bb7a47193f986a539351c861f200b6ca5b0ebe8716a95e1b
internalDatabase:
  persistence:
    enabled: true
leantime:
  sitename: "Leantime"
  language: "es-ES"
  defaultTimezone: "Europe/Madrid"
ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Leantime"
    gethomepage.dev/description: "Planificador de proyectos"
    gethomepage.dev/group: "k3s"
    gethomepage.dev/icon: "leantime.png"
  tls:
    - secretName: leantime-general-tls
      hosts:
        - leantime.vicsufer.xyz
  hosts:
    - host: leantime.vicsufer.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
