---
image:
  repository: leantime/leantime
  tag: 3.5.12@sha256:9fba9c119d5a8f4c53e05fba822ed2d066f7ecfec29d13f218a42aab302a445b
internalDatabase:
  persistence:
    enabled: true
leantime:
  sitename: "Leantime"
  language: "es-ES"
  defaultTimezone: "Europe/Madrid"
ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Leantime"
    gethomepage.dev/description: "Planificador de proyectos"
    gethomepage.dev/group: "k3s"
    gethomepage.dev/icon: "leantime.png"
  tls:
    - secretName: leantime-general-tls
      hosts:
        - leantime.vicsufer.xyz
  hosts:
    - host: leantime.vicsufer.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
