---
deployment:
  repository: ghcr.io/we-promise/sure
  tag: 0.6.2
  env:
    - name: RAILS_ASSUME_SSL
      value: false
    - name: RAILS_FORCE_SSL
      value: false
    - name: GOOD_JOB_EXECUTION_MODE
      value: async
    - name: SELF_HOSTED
      value: "true"
    - name: REDIS_URL
      value: redis://maybefinance-redis-master:6379/0
    - name: DB_HOST
      value: cluster-maybefinance-rw
  extraEnvVarsSecret: "maybe-secrets"

postgresql:
  enabled: false
  auth:
    existingSecret: database-password

redis:
  enabled: true
  auth:
    enabled: false
  architecture: standalone

ingress:
  create: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  tls:
    - secretName: maybe-general-tls
      hosts:
        - maybe.vicsufer.xyz
  hosts:
    - host: maybe.vicsufer.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
