---
image:
  repository: ghcr.io/ellite/wallos
  tag: 2.52.0@sha256:fe34f19e958fc486767d2e998a6bc4f37ba81609d3dc0540d98b9ebc05fa1c3c
persistence:
  database:
    size: 5Gi
    enabled: true
    mountPath: "/var/www/html/db"
    storageClass: iscsi-retain
  logos:
    size: 1Gi
    enabled: true
    mountPath: "/var/www/html/images/uploads/logos"
    storageClass: iscsi-retain
ingress:
  main:
    enabled: true
    integrations:
      traefik:
        enableFixedMiddlewares: false
        enabled: true
        entrypoints:
          - websecure
        forceTLS: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Subscripciones"
      gethomepage.dev/description: "Registro subscripciones"
      gethomepage.dev/group: "k3s"
      gethomepage.dev/icon: "wallos.png"
    tls:
      - hosts:
          - &host wallos.vicsufer.xyz
        secretName: wallos-general-tls
    hosts:
      - host: *host
        paths:
          - path: /
            pathType: Prefix
