---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/vicsufer/homelab.git
        revision: HEAD
        directories:
          - path: kluster-manifests/argocd-apps/
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/vicsufer/homelab
        targetRevision: HEAD
        directory:
          include: 'Application-{*.yml,*.yaml}'
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      syncOptions:
        - Validate=false
        - CreateNamespace=true
        - ServerSideApply=false
