---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: domotics
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-apps/domotics
    repoURL: https://github.com/vicsufer/homelab
    targetRevision: HEAD
    directory:
      recurse: false
      include: 'Application-{*.yml,*.yaml}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false
