---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: cloudflared
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/vicsufer/homelab
      path: kluster-manifests/cloudflared-extras
      targetRevision: HEAD

    - chart: strrl.dev/cloudflare-tunnel-ingress-controller
      repoURL: https://helm.strrl.dev
      targetRevision: v0.0.16
      helm:
        values: |
          cloudflared:
            image:
              repository: cloudflare/cloudflared
              tag: latest
          ingressClass:
            name: cloudflare-tunnel
            controllerValue: strrl.dev/cloudflare-tunnel-ingress-controller
            isDefaultClass: false
          cloudflare:
            secretRef:
              name: cloudflare-api
              accountIDKey: accountId
              tunnelNameKey: tunnelName
              apiTokenKey: apiToken
          replicaCount: 2
