---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: cloudflared
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/vicsufer/homelab
      path: kluster-manifests/cloudflared-extras
      targetRevision: HEAD

    - chart: cloudflare-tunnel
      repoURL: https://github.com/pabaquino/helm--cloudflare-tunnel-v3
      targetRevision: "kit-ar/main"
      path: helm/cf-tunnel-v3
      helm:
        releaseName: cloudflared
        values: |
          image:
            repository: cloudflare/cloudflared
            tag: "2024.11.0"
          cloudflare:
            tunnelName: homelab
            existingSecretCred: cfd-tken
            protocol: quic
            # https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress
            ingress: []
              # The first rule proxies traffic to the httpbin sample service named web-server at port 80
              # - hostname: tunnel.example.com
              #  service: http://web-service:80
              # This rule sends traffic to the built-in hello-world HTTP server. This can help debug connectivity
              # issues. If hello.example.com resolves and tunnel.example.com does not, then the problem is
              # in the connection from cloudflared to your local service, not from the internet to cloudflared.
              # - hostname: hello.example.com
              #   service: hello_world
