---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 8.5.1
    helm:
      releaseName: external-dns
      values: |
        provider: pihole
        pihole:
          tlsSkipVerify: true
        # extraArgs:
        #   - --pihole-tls-skip-verify
        #   # - --annotation-filter="external-dns.alpha.kubernetes.io/exclude notin (true)"
        extraEnvVarsSecret: pihole-secret
        sources:
          - service
          - ingress
        extraDeploy:
         - |
          apiVersion: bitnami.com/v1alpha1
          kind: SealedSecret
          metadata:
            name: pihole-secret
            namespace: external-dns
          spec:
            encryptedData:
                EXTERNAL_DNS_PIHOLE_PASSWORD: AgAU0cEVAhrDIJFi58DCIEXYfH1Xn+5eUIcSZXsxFrz3wimk4QaLdhF3VqpOGX9kaKyHxE79dyCzDjnCXnjK5yBS/RFFPTRBu9hjU6J7xfP7y8Aa4kN56gft/XybWPyXSVCb0/AlqC11w0LDnP5DS15MCHRe5YeZxsPLSKMVXHfMlOJQaK55HDx+XEiViXlt5KjRzUT05B5eFgDbqSQ09nJXPaOs8Fp4o1PwtBSMMglZqHBH4wyrsSGp8eUu64zf4G0hooyVBL5EWYsj+FA98H8M+5r8CubHDQwR3O3V6OeriVGH14K5sPZ8IBPOWGTsSugwHAUPgZMNyNbPl/2mv9/phkUl3jeEHfMS3jqvi1aTfnAtfOFNpuWSBeSoVxwyU77Np7Qji+uFatVEu3I/O5daswRwcKm5QaXfu5FwfZ/P7j9QCKLt25nJsFXBP4536OMORaMT+E72klojpReBZWIl1+oEL5Du+fFyH56Kuo3JDAfqxBvyumVJMQUKS6v6R+72YKXjcdkX7/3R3xh33FkMKlf8sgHukmoHu/WB8xqDXeKnIiRt4TQHxvVlEPr1Kph/dvuxF3Wvv43Z9UV8B7xDcx/n6oJIJCQC/z9bwKLHEsfYFuuNUcL2958sHv4pP41x3yOmcY75gbNhrLRV1BADD59LxCge3VGCngeRnw/eC5qqgtL5GJ15GWGcRyBCCyPdEUAQZ2mhgQ==
                EXTERNAL_DNS_PIHOLE_SERVER: AgAK+yvPLSTFYdvHeILnBEbAj18ONkWUBnBygFZbOJkkNW/t68jRZGoBvdco4/xOZPjwiK2Qda+21iNYY3FuAmYk+9ODW5etoHCbIcIrNZOR6fakcj3nBfN53EVWnhDoKVgj6//NBWguHQDkMqGeyvmRx3aFBk200NMVX1/hwNrktrzb5ZysFmpBpAsG8V7PJ7XlZ0UwnrLbBJL/z4bhUjMk3f07v1k3Mc5JM5Mg+2/OjMpt5TQnptWZ/FnLpOw+GxlS5VODEHPLxVdY0QtjKC1iges1boSphSqaQfcSkpiy7tMePJqdWpyB0udeXF5qgee+mdzXDTEB0/uq6iJxIvgs8iMm3ezGF31ZqSjmS3BL9RXGq1em9yw8bcIXWm5Tr6/laBauP2JxTzmuT6NgxajhHXm0dgajswLUO6Tnb0g5UkjI4H0KlSOy3Y4ku6L04wl5WdZoSMCbBLlucFq7b8KnLrL0Ot33PqvMxhnK9aJSIAqPHDXlDCvRt+jIStNMZ+Edb6YZZ6Sn3KEMYvarW6cXwm5NxinO0UXf8YNHcg8OXN0WIldLg88+jqPxqp8KQIs0f48sdy44nnj5qHWLiRN7NWJWAIXdGr9STrUyGDjNREqgbGVqmtKDJrBtdFqsK0WFYtXu8DNqHGPDqgAA2yg+0YmgZbzLsyC8D6v6CS/vILQpsHgqnsXBqgASpNP3NLU6CQjqviHXhcBTUEbXjoC6p9ZawbGN9Y8=
            template:
              metadata:
                name: pihole-secret
                namespace: external-dns
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
