---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 8.5.1
    helm:
      releaseName: external-dns
      values: |
        provider: pihole
        extraArgs:
          - --pihole-tls-skip-verify
          # - --annotation-filter="external-dns.alpha.kubernetes.io/exclude notin (true)"
        extraEnvVarsSecret: pihole-secret
        sources:
          - service
          - ingress
        extraDeploy:
         - |
          apiVersion: bitnami.com/v1alpha1
          kind: SealedSecret
          metadata:
            name: pihole-secret
            namespace: external-dns
          spec:
            encryptedData:
              EXTERNAL_DNS_PIHOLE_PASSWORD: AgCGkpARm5UNnjutJHaGzBmaj0SRHZcA3XRhqkQk88LkjXlipQLEQIsMDiofKRc/7Vdvz+FDgWHs9nVg8c0A1BLbSGTVxxZDKi+yVhfZA9M3Xjv6Uw7W3ReSRkppQlNP2TeMFbsa2lDv8MBqfssERH8aYpPzHZZ8nP06zLSi1P05XjVwsO7O7QmOlw5YbxmN4fIdLNucbIeNaN/O5kcUGq3WPIavQimFIeJmzGHuU+hdgkdDzmTGgBH9vJtJBjlqPfA09cWEjASy+qLz98SJw/HKn04uyaymV6+WGTpGzcW8+6XB339l3eytxarwVa4QrLQIAxCjlG4enhFQ9lmS/MUX+GjHmG+slipVv53wh7lYBsShEBDPsIUvFzOE0dAUuWN3oCaSY1+YX7rMLrYp4VXDTHv+Qcpm0G7tAt6HgucPp1W/FgTOqqt4mM+syu9nXr7VzqMRZW0NWvWlve7hSU9nDxnO6VE6xLxmHBCDjJ5W6diRfSZbphHbtnNHZATcrJBjSBuXNtYTjO7D2opDA/LfHBHStI00DZPZunW3JNfvUjkifsNgwEd8UibHq1U5baJaN4aNXjio/5B8Dh0Npvc0WGkI8m8W7MOlo33eciSsK6QjFAbe/IYjsDoZcn1pZBVDZwv+kTcbJGmUReZT/sWaAd1ahxIsSKV5qX134ldS6D1h454FjGm4+RlEFIH9AqHExkvnerov4sm7Wq8=
              EXTERNAL_DNS_PIHOLE_SERVER: AgBAIC95fABziCs+IP0rLT62tJMq29w2WFYXO5OALtONZDhAEjfPH2BT/ab5vLavtvbLn6nToTc+yfYpG5E5Hx5yFqVt9XxTmFHs26vEaxDwK8G/sjURr0cyibzPnU8is5uz+1TzzZKigDnBf3qy2XMEaz0PDB0PBqhc/7eMofVpVRirHZlOErEbsQSs75OhVY7zOkOx5hYmwry3gRjLBLplctD8aeL7VU7lcLO8U3sYhx9J2gFj2EPua5ayQ2zHW7rfEQjd4NrPpVVceuVdZ1u8Bh1ic3i0kph7cMyGvYb94dpSCbQC45zpb8o7Ql3A7xCP4oYtuyBaE5rq+WQd273uF7AOY9aYa67mP8Xl+wzy0KM06pJ2qJvB+GDhC2hfxKXL7z7bE5tk3Db9PkEWdnHCTeopZ15wtxOTazDAwxORsTNz/rcrnQv+aMGv95n59WqEQUYiMB6SxFk2Hf+tB/fO4hamOZE1uleZlCB1i2b3eZxUDBz+L85HxsP8FLmOo70kp77IAbrOS/yycdcMONNB1i32dx+2awst5LW08/9DNWlxwfGzKOpqCeNEUKD4U3HesOLl/bcwWBp2ZQA1UrHrJ4BFU7GEj2yHMc++9hYbqdlMpIiwAHaux5nbT48iFtLyfl4m/RnC7A1YQP4JAySNEKf7nyWUr632N85qjs5OplutjBiaAm1DhZSLCqN4RZskZaGTP7aF37BrFFxK3JMCD8NmbidPTjaRV5CSscCurw==
            template:
              metadata:
                name: pihole-secret
                namespace: external-dns
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
