---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 8.5.1
    helm:
      releaseName: external-dns
      values: |
        provider: pihole
        pihole:
          tlsSkipVerify: true
        traefik:
          disableLegacy: true
        extraEnvVarsSecret: pihole-secret
        sources:
          # - service
          # - ingress
          - traefik-proxy
        extraDeploy:
         - |
          apiVersion: bitnami.com/v1alpha1
          kind: SealedSecret
          metadata:
            name: pihole-secret
            namespace: external-dns
          spec:
            encryptedData:
              EXTERNAL_DNS_PIHOLE_PASSWORD: AgBDgcJUbGMtxT6PDMDqb/felszK+YQz0Lh4sdnwWn5UAphdhKTWo0fiTJOaZjuEGBEcVloOFkRi6m/PxX27PwpP7Ov59jMJNjpgI3MXE0rtT8gAGfzfK6vuE+qGil9EsYLlzRTkHfVojuersa/0EhSk/uH6P0R2dMzIIYK7qzfV6jXlTrMVidPUYEn+sd99L8w375PHoCpMsEtdCuQZj28XIJGc+y+pfxNUZpTbcEbrOmGf+KILcYBDp7Y0tNMU5toH06MU/yj9/cY55RAVHkDUYbkdCco9fknbeVrZ5WBH6Vkeg2qsestjziUWNxzxuxX4AU/ItRgfa1SVwqXYDnl8Gh+Z5UdIsWsRcS6HWHW6w8DAeDrjDzTswAtzSBUMReUDNuYwZ4chX1dNZBpUF33ty2BzS68M1JU1Kmp5Pv1WxsZiY9KNG014Cb3JXeJczv8iIpvmIX9a1f452hxfn8AMSCRQnLKK4V1Vu9pKFGkbrGqGmleYJzwJYBY6uOxabpmRV9lNdCguxo2/wWCbOsczq6dQn36PBhdpq/aIsb4wK5g1sURFgSBJQJlOVoDFLEorpog0hG3OJWQB/hyab5W42dw1POV5IkSnjlUcsqXZcrcy9joh55a8YTqf1exJDsK7yYY/z4DToOWX1uC3jTxPpkiC4ZYzmO7WyncOeTlDkTcd9efVZ/u7NidCR0mkU0WJ9QGbIxQj+gtSUEo=
              EXTERNAL_DNS_PIHOLE_SERVER: AgAQ3qXxIkQ1/h6ddMUnxDIjbpLPpNy322GUI52nWr3xvFYCmlgXN3z/MCM57hmXH2zg+DOWOgKsd4cTrmEzuZn/NU3fVqDrNAY1ygUT1TKwoC9oaY3paeTRIx5Vt/Nw+whs/0kpKlApa2dXFofr3OZ1oHgk1y+kbhtqyqYmfkSe0q6/3xXmlNi5ADzdW/n/gDPOKGTa0C1Bn3z/cA92x87rs7m99zuZuuvdJt9UBOjuUunmD7jmovHXWQLNh9mk3j2YBKWp+H0XEH4gHXgmMjThPu+wGfIFQKzGwyr8VYCA5TFDnS+9cBb1dgDjOkq50hzuc0AnJWSE3qpdy4ystyTvkR1jg2PsKaCYXZgrdkmXtLcAu7rSd7zAiX8qS5s9G89RzJ0C4JGFX+ouLbVY3tWMivhHDtFmAD7ewhWZoAS+YToSRwBeU8CQVschCrFpKTCyTZrx1Q4PFjaJqmUNHhpaobCpeRl0F3yANYOPAicIkd6h0EIoLU4caBGKYV3ozyOHO0Za3gWtinbhgJMsfmCFjOpuPj1ek/dpR2m1NUX0Q87OrpqEdPQXNXoQTDNxt8fQveY7zmelRuoFT0ysr3lpxrGF64lGbHpdO0zRihh/GEHp7IHcb3fSJKyC8Xdpuu4YkHl4l+puN/UopBC6A2STBXAMXZZJ0hniYlq72FZnlE6BzAp23ZJKBYgzkRHgWsbIpj6h7XeicDjg3Bq1vrNpbbL1wcdzIyQ=
            template:
              metadata:
                name: pihole-secret
                namespace: external-dns
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
