---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://bitnami-labs.github.io
    targetRevision: 2.16.2
    helm:
      releaseName: external-dns
      values: |
        provider: pihole
        extraArgs:
          - --pihole-tls-skip-verify
          # - --annotation-filter="external-dns.alpha.kubernetes.io/exclude notin (true)"
        extraEnvVarsSecret: pihole-secret
        sources:
          - service
          - ingress
        extraDeploy:
         - |
          apiVersion: bitnami.com/v1alpha1
          kind: SealedSecret
          metadata:
            name: phiole-secret
            namespace: external-dns
          spec:
            encryptedData:
              EXTERNAL_DNS_PIHOLE_PASSWORD: AgA3G25FvXwvznWkfhduvrC0n8LO5siJ5+8axu8sZ1+NnHN9Hjoc3ymuj7ENfaH2hEPuRlyMhyJd73pscFz1jl+XdSg4/whamCiUQXUU/B9C7XWV8i993GiJYubCxeraXB1GCIBoRJlwyOI/5RGXWShldYCCPaSSFCMVqPcUmQoEfs+gY2v2WWGnAUm57f2e78IU6wRfCo5Q42dx6zzjWuZH0AzNQz46ohAlE35mKfIl373rSSfcpsjH3VXAlIh4ZDo9PCbxQs+FJSFplWbOlh6iSmFcOPnmKNzo2VtWsI3BtsA+w4ykPNaORRYsJlPulcqy6UeAY8RY5orskFD6yM6FnlaR1YwD5v3vy9R2Z3ZgAmA6SyqcVApumrrIpfvvPMZ5dFba1AZx+EqOMhhdTWo+BwnJKH80oqk6EAN8xTmqaXs5CPcr3vVNTAOw0KVN6TswdltI9NfjzgG7U6BMPW9G+7/MDG/x0tSRhIBChoQjXrmaEfBvA9JzEOvpXMAEexwmXrcjN+8h8KECdcrOruJsl9xKTk0emS9d0+7N3D0VQkxGfJ6ezYwRgcQe1b9pKgYkG4tqwyDvOsvqN+bD4baWInBwKHH/mm+/Ze1TMn7fV8wFvFzXPckvio82Qi5jqBo91K7iL0Hv8RFK5Xz8GOyVH6RBJJ7cLSvHyAdAb3soOdnHDbu4vP15YUnyFaJufhwvKcmnHgKS2gxtAp8=
              EXTERNAL_DNS_PIHOLE_SERVER: AgCQVr+AU00oFV//69+SIka0zNvxbchrMuIEdiNCsQPOYMj98R+ouNFtXjbuG5B1Ow0g40WRbJNEA8UP7PbyoJzb2hfd4zVDHy9gRdES6oThOObrtxFyjfDQ9KoKjemRMARDIh5eqbTNusF9T4y1cCBt8LngIuwUVkbT9ZF4NfMdlu66EelTZafpmAkPwhGDhnhG52KUsiVS9cY9wh0ajD5sOtFxTYJwXIJC3oSGgJ6L8K2FDjWBdW9OnjUG8mhtYSDiD7BKY3oshfZCfa47nzdlb9inOacZcDonT533fXyjBzhOzcPMaNSajfCD7j9gGb119n8Cc/t4fi0oi3Gi0bT0v5cC39iQWUDRfP9czdvYae9VPyS0RubQ6hec3IlJwig/ULF3qhKkVZyqyBSpUkvwWmM/UBmx+VyWPitGrnph2hLliMocTDBDWJrQo3E2CPjptEvcypF/8M3hggoaIWTRndp+DRIyDKkj/wKDZPI5BYPPa5pGsEquYAS/abZBmtOv2nu8kewdhXaUBDhlaq05WkjKWFy/6/u8/ULW9MqoyxPw/hEm6C9DPdXyWBig/QLmYFJXH4ijgFiW6tU9N7nGEd6fBwBIaLD1o4VirMW0zcQkFZmr/BFFXi+ps/1sUj5lHeehkLYosTYbet+gAp5PwPWxh02sra6eoLbqYZO4Do0NU8R4+hvX7KcpAFXzK8gBIim4uW/IbhqGV0RTPXh8QblQV2grC4r1XTaLobHTyw==
            template:
              metadata:
                name: phiole-secret
                namespace: external-dns
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
