---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 8.5.1
    helm:
      releaseName: external-dns
      values: |
        provider: pihole
        pihole:
          tlsSkipVerify: true
        # extraArgs:
        #   - --pihole-tls-skip-verify
        #   # - --annotation-filter="external-dns.alpha.kubernetes.io/exclude notin (true)"
        extraEnvVarsSecret: pihole-secret
        sources:
          - service
          - ingress
        extraDeploy:
         - |
          apiVersion: bitnami.com/v1alpha1
          kind: SealedSecret
          metadata:
            name: pihole-secret
            namespace: external-dns
          spec:
            encryptedData:
              EXTERNAL_DNS_PIHOLE_PASSWORD: AgB5g5K9ZX7AWi1+k7sddUAL6knbUxwe2fI0d+6BA04oELfmo2Y3A6ZlzKIb02ynF9vEOuRUUtRqTMRXqv3ds6glpWQmrVQXQhLZCMKjvSOQJJS8NXHq4w6qqIWypwkadLV0+IU8Xez+qlttLsOtVSixAFH1FP8gy/ODmRwmCG6+JumFudtaUBViOuPq5YlimoMK5LUR+Qu7I56Qw36k/gu3FDHrXBYHm+jINZnMybfFrBn7LJH63Pgu4nQ1cE2JcYX85EobGXOQ53csqFkC16LexqpRKpDWTyREb8JPteme/AU06vBSh8d+OLkrCZVjiGkLOBzRYCTZflc85HvgCFgZOnoZ+5z4FFdnM8dMLB3+sOogp+hf8CzlXQG7hnS62k87c8xfjEpHByWgL+3ILO5MFNWbAYas091TmI8cX99FAPGJq75cO3pWz/OY9nxrW6ghZBKQEhxBP61PpWXDeZtZdr2MbrbzfowY1Iqx8wGbIH15g8nKWsO/TQt3GyVWY4hwPwszj7iwjrPI9nq0IdhdUMtSjtuR2u014A1MaTDWmKF8rOnIo0emoojFBn1sd6CAV8ZY/eg76ZUa97rSYLY65wQRJ9bVfs9YPNyjznPd26nSJwv4eNk+cscy9mEjSGBpW2Ze2vO1BdDNZOmwyp+iVJyre4JRmR1225MhaoLv8HOLiVh88J4AahSuLM17o6iuY0KBh3GTFZ3CJzer3Ref6V2upNg/
              EXTERNAL_DNS_PIHOLE_SERVER: AgB9Ryuw3M+VtkSnqwMl3DNZK4Wxh5ON8BYgDXeS9RajCdWdSOEEdT6peVzKVJpJVMaAAxgaV6w5Ea+wS6f/wgiGpu5aFzx985RbOQqaKafDwQcbzvU/RjkEUNmNJ2wUGzo1TxTFG/GPv1EOPAFF02YmjAhIIzwF5eiggKTcCLf1xUbH1RD+a3YhpZ6kee9uU9PhbLfzwpSuXtuJE7fvX+ND5M82fUqGNWoXpaOXMmfZ5UMPtgrYXp1udypklJZgFRajVVErT7QzoePdjLsONNgBu7fNdd431K2Vf44GbDhvtCyR5jFuUDtD1v04ywUJkdRgpz3HXYG/vj0QyoDWb3opCMK0DQBB7qQru3MBqEGcoMCenRfkuJIMKCAiYdb4JsT6nXNNytPHSucJkqy21Csh4cPq6pLfpZN7bwdWBOTqoDDuT/lfI6wtWTvBOAbrr25CGFrn31rH0GRmoXCNzqJ8gTyOMyAkkjWhDVBvf+8IH6ksoD+hbauSdYK1AdEJswHVdMfeesdP4ZgpzgrTZqmRWaSZ4MS+Sv1XMvWrvdil0XUrE7rwTyNqrdTA19IxNwucWRXbmf7FOvrEzu8rWdBbz6JXn3HZmWu6Wfy57DpkmQoIxaDfO3oN6xmlgOJ6NBgDIsxKQ8FkoCA4YcOU0+ABsJwMm2h1QbasfoKGihO4fjOKSAcjmHleBY6Iv7TvcUzrDk1OAcsgJZQDkW6QYaiFfE8WV+6wjTc
            template:
              metadata:
                name: pihole-secret
                namespace: external-dns
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
