---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: firefly-iii-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: firefly-iii
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/vicsufer/homelab
      targetRevision: HEAD
      path: kluster-manifests/firefly-iii-extras

    - repoURL: https://firefly-iii.github.io/kubernetes/
      chart: firefly-iii-stack
      targetRevision: v0.8.0
      helm:
        releaseName: firefly-iii
        values: |
          firefly-db:
            enabled: true
            image:
              repository: postgres
              tag: 10-alpine
              pullPolicy: IfNotPresent
            storage:
              class: "nfs-csi-retain"
              accessModes: ReadWriteOnce
              dataSize: 10Gi

            # environment variables
            configs:
              RESTORE_URL: ""
              BACKUP_URL: ""
              DBHOST: firefly-iii-firefly-db
              DBPORT: "5432"
              TZ: Europe/Madrid
              existingSecret: firefly-iii

            backupSchedule: "0 3 * * *"

          firefly-iii:
            enabled: true
            persistency:
              storage: 10Gi
              storageclassname: "nfs-csi-retain"
            config:
              existingSecret: firefly-iii
              env:
                DEFAULT_LANGUAGE: "es_US"
                DEFAULT_LOCALE: "equal"
                TZ: "Europe/Madrid"
                TRUSTED_PROXIES: "**"
            ingress:
              enabled: true
              className: "traefik"
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                cert-manager.io/cluster-issuer: "letsencrypt-prod"
              hosts:
                - firefly.vicsufer.xyz
              tls:
                - secretName: firefly-general-tls
                  hosts:
                    - firefly.vicsfer.xyz

          importer:
            # -- Set to false to not deploy the importer
            enabled: true
