---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: traefik
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: v33.0.0
    helm:
      releaseName: traefik
      values: |
        ingressRoute:
          dashboard:
            enabled: true
             match: Host(`traefik.vicsufer.xyz`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
        deployment:
          podAnnotations:
            prometheus.io/port: "8082"
            prometheus.io/scrape: "true"
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
        priorityClassName: "system-cluster-critical"
        tolerations:
          - key: "CriticalAddonsOnly"
            operator: "Exists"
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
        service:
          ipFamilyPolicy: "PreferDualStack"
