---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: synology-csi
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: synology-csi
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
  sources:
    - chart: synology-csi
      repoURL: https://zebernst.github.io/synology-csi-talos
      targetRevision: 0.9.5-pre.1
      helm:
        releaseName: synology-csi
        valueFiles:
          - $extras/kluster-manifests/argocd-apps/infrastructure/storage/values/synology-csi.yaml
    - repoURL: https://github.com/vicsufer/homelab
      path: kluster-manifests/argocd-apps/infrastructure/storage/synology-csi-extras
      targetRevision: HEAD
      ref: extras
