---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: synology-csi
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: synology-csi
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
  sources:
    - chart: synology-csi
      repoURL: https://christian-schlichtherle.github.io/synology-csi-chart
      targetRevision: v0.10.1
      helm:
        releaseName: synology-csi
        values: |
          fullnameOverride: synology-csi
          clientInfoSecret:
            name: synology-csi-client-info
          storageClasses:
            iscsi-retain:
              isDefault: false
              disabled: false
            iscsi-delete:
              isDefault: true
              disabled: false
            smb-retain:
              disabled: true
            smb-delete:
              disabled: true
            nfs-retain:
              disabled: true
            nfs-delete:
              disabled: true

    - repoURL: https://github.com/vicsufer/homelab
      path: kluster-manifests/argocd-apps/infrastructure/storage/synology-csi-extras
      targetRevision: HEAD
