---

- hosts: all
  become: true
  tasks:
    - name: Install packages
      apt:
        pkg: "{{ apt_installed_packages }}"
        state: present
        update_cache: true
    - name: Set up multiple authorized keys
      ansible.posix.authorized_key:
        user: "{{ item.user}}"
        state: "{{ item.state }}"
        key: "{{ item.key }}"
      with_items: "{{ ssh_authorized_keys }}"
  roles:
    - role: hifis.toolkit.unattended_upgrades
    - role: sshd

- name: Kubernetes
  hosts: kubernetes
  roles:
    - role: k3s
      tags:
        - kubernetes
  tasks:
    - name: Increase UDP wmem_max Buffer size # Quic protocol https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
      sysctl:
        name: net.core.wmem_max
        value: '7500000'
        sysctl_set: yes
        state: present
        reload: yes
    - name: Increase UDP rmem_max Buffer size # Quic protocol https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
      sysctl:
        name: net.core.rmem_max
        value: '7500000'
        sysctl_set: yes
        state: present
        reload: yes

  #TODO
  # - Autoregister k3s nodes to NAS NFS shared drive
