apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.mqttPort }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
    - port: {{ .Values.service.mqttOverWebsocketPort }}
      targetPort: mqtt-ws
      protocol: TCP
      name: mqtt-ws
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
