---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: prometheus-stack
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 69.3.3
      helm:
        releaseName: prometheus-stack
        valueFiles:
          - $values/kluster-manifests/argocd-apps/monitoring/values/prometheus-stack.yaml
    - repoURL: https://github.com/vicsufer/homelab
      path: kluster-manifests/argocd-apps/monitoring/values
      targetRevision: HEAD
      ref: values
