---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: metrics-server
  namespace: argocd
spec:
  project: homelab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - chart: metrics-server
      repoURL: https://kubernetes-sigs.github.io/metrics-server/
      targetRevision: 3.12.2
      helm:
      releaseName: metrics-server
      valueFiles:
        - $values/kluster-manifests/argocd-apps/monitoring/values/metricserver.yaml
    - repoURL: https://github.com/vicsufer/homelab
      path: kluster-manifests/argocd-apps/monitoring/values
      targetRevision: HEAD
      ref: values
