---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zigbee-ca-cert
spec:
  commonName: zigbee-ca
  duration: 87600h0m0s
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: zigbee-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: ca-root-secret
