---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mqtt-zigbee2mqtt
spec:
  commonName: zigbee2mqtt
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: zigbee-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: mqtt-zigbee2mqtt-cert
