---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mqtt-server
  namespace: smarthome
spec:
  commonName: mqtt.example.com
  dnsNames:
    - mosquitto.zigbee.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: zigbee-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: mqtt-server-cert
