---
cloudflared:
  image:
    repository: cloudflare/cloudflared
    tag: latest@sha256:b77d84e8704db38db22c22661cf7e56468c526e3a6a5fe9c8b7c151452fa1472
ingressClass:
  name: cloudflare-tunnel
  controllerValue: strrl.dev/cloudflare-tunnel-ingress-controller
  isDefaultClass: false
cloudflare:
  secretRef:
    name: cfd-tken
    accountIDKey: accountId
    tunnelNameKey: tunnelName
    apiTokenKey: apiToken
replicaCount: 1
