---
cloudflared:
  image:
    repository: cloudflare/cloudflared
    tag: latest@sha256:eb5c9324efe3b8e8a48612423dd912f76fa93cf138923e7eda5d1a9805057757
ingressClass:
  name: cloudflare-tunnel
  controllerValue: strrl.dev/cloudflare-tunnel-ingress-controller
  isDefaultClass: false
cloudflare:
  secretRef:
    name: cfd-tken
    accountIDKey: accountId
    tunnelNameKey: tunnelName
    apiTokenKey: apiToken
replicaCount: 1
