---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBK4NY4rz+q+4oJhsZ7HDc5vrSPdOC3CsyjUzQp4BxnzQhnI6sBxxQXwdNrpwi7Gva6JMX2lgvXacT/zv2KxrkM5CL7NdzaPwHxipcc/dpPpBHga3A7Wp2wDESyuYSJfItzdaWBVznLTpBHGSf8eYVjZ0nQR+EEpOssf6+mK+W3oKTwWIdyjgT2El1P66n108xZeDL/V43iWmcbDYJKDiHDQ5M/ii6zJtQ5wfMm8P24PO8ostMwuMFreDeAhoo5VbIET5rGEGTDl76cV1n5uSvbi+r2TTbbAD+1sxjTHSOi99wqYkLvor8fm8np44jI3K7ioLh/g8OUW8jO6/soWX1DLmMdG8e860yG1D17pwgN8GxONsLbAA5y0JdN6pHF/ifJG98RVsuRKO28eDlgb1j1+e8PvlM/D8SW/keOehuqEMeFYWr6PWTldd2sLNCWPVnfh/CLl+4z4P1G5KhQvf65lQJNxTdwMyA78bx9tQuRNDMfCQwevxY99d9g/Of8/T4HBDH+BNb6f1ltgjS6ytcM3r67zKl7nCou+lk/ZG5Ye11XXC3ZQAL0OoCzESLf9obkiaZ0Kyv/B41oFNhF8NkKmAPT6wCcWAM9wzpdTUC/calx4tLagah7RcKAQua8wd26xXfW6Z7QE9JAGyjgVYx9U72Wc8hDt18sazaXwj+mk/BBGIjBr23RzRJjUytWuyYFLG1PjNeZzU72cMUri4U/XA==
    client_secret: AgBXQtKJnrGUt7k/xKVrQvmjF1w9MIbY77Uxr8DwiKjGLBlow1Rq1g6HAXow0T/hsAB1nhGzpRVzV1njMWZ0y0xlPEL87vPk+vijv3UllL21RFXuZNW6v+Orjr/pcmj2qWg+JWX/PJ9ID9lCLuMD7p/hsAmPHD2Dlh+zJKxIfz7R0FP9Cv5ahYR4bSOLaO34RJivwoP8kMCXEaBif6WYmXf/dmIP4gqTTyzHtjCd2gjFvs0puGoRWqFKiYGolM+hcNcWzuRizKF4BPmW45Bzy9j2S6XL8jo0mzNqxEL4yr0Fr5A6TVLV09mNYVvaxVvV/8O1VnPA5wJAko6n6lKVaNVWtQAgyMumqvBhUYTj4bHWj81ZW/dGk1j65kf7hp6qZLpfSUN3fgmHEvWegzk8Xct1B+VcuMumUCw3wjnnE+y4mJS2hP3R0f5PkeouvgVfKJ0mGXC1kBjwlQYbX9x4/vX4wnSypsZMAarpvKGNccCrwIoGZS6A+UM8z0ukinrJ7LO7RCD1Z5LqatVp/91JjR2bCfnaowatUgbEnuG6PBHYHvEjSIPlk5XWkT/E5jAnV0Z8UCLNGfB8PNY5g+I10QsPtqjYSNJOQz1gQZ43ym2v4wU/FRQ/HjC6Mw6KWQww1Rx+UBeyUSiYZ5DZmenp5MW/Cc4i5LvnhClHkDSR/+ak87hxvEEnTc5aGPdTNwn7x3SKsKE4rhDiJ9DvQTgO4VrFWOI/JHGG3ZbR64KYTG5PKH6Po2gwyCQ/74dsXAmcSlWIwN2rHgINzl6PUZvZoIo=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
